title: Murad Rzayev
description: ADA University student | MERN Stack enthusiast
url: ""
baseurl: ""

nav:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Projects
    link: /projects/

social:
  github: "https://github.com/muradrzayevf"
  codecademy: "https://www.codecademy.com/profiles/design3101113444"
  repo: "https://github.com/muradrzayevf/personal-website"
